### ISSUE TITLE
Upload image generated 

### ISSUE THREAD

**Issue by wnakano** [basetenlabs/truss#1037]
**Describe the bug**
When attempting to upload a file to an S3 bucket using the boto3 package, the upload process enters an infinite loop and never completes.

**To Reproduce**
Initialize a boto3 client for S3.
Attempt to upload a file using the upload_file method.
Observe that the method never returns and the process seems to be stuck in an infinite loop.

**Expected behavior**
The file should be uploaded to the specified S3 bucket, and the upload_file method should return successfully.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - Environment versions:
    python: 3.10
    boto3: 1.34.144
    botocore: 1.34.144
 - Truss version: 0.9.21

**Additional context**

**Comment by squidarth** [comment]
Hi @wnakano  -- there's an issue in the boto + truss interaction, there's a fix documented here: https://baseten-knowledge-base.help.usepylon.com/articles/2415834368-how-do-i-fix-the-proxy-connection-error-when-deploying-a-model-to-upload-images-to-s3-on-baseten
