### ISSUE TITLE
async requests without webhook_endpoint dependency

### ISSUE THREAD

**Issue by wnakano** [basetenlabs/truss#1079]
**Is your feature request related to a problem? Please describe.**
Based on the async request [documentation](https://docs.baseten.co/invoke/async) it seems mandatory to have a webhook endpoint, even though it is just a mock example, in the json data passed as payload. Although, for use cases where the output is being stored in a S3 bucket the webhook dependency is not required at all. 

**Describe the solution you'd like**
The idea is to avoid the mandatory usage of a webhook endpoint when using the async endpoint.

**Describe alternatives you've considered**
While requesting the async endpoint, the parameter webhook_endpoint becomes optional. When an user set a value for such parameter, it will post the response on the given endpoint/url, otherwise it will consider that the upload process (such as to a S3 bucket) has been already implemented on the model.py procedure.

**Comment by helenlyang** [comment]
Hey @wnakano, thanks for trying out async! The `webhook_endpoint` is actually an optional parameter--see the [Quick start with saving model outputs section](https://docs.baseten.co/invoke/async#quick-start) and the [API reference](https://docs.baseten.co/api-reference/production-async-predict#body).

Could you try calling `/async_predict` without a `webhook_endpoint` and let us know if you run into any issues? We'd also love to get your feedback on how we can make this more clear in the docs.

**Comment by helenlyang** [comment]
We also appreciate you taking the time to open a feature request!

**Comment by squidarth** [comment]
@wnakano let us know if you have issues with that approach!
