### ISSUE TITLE
Any way to add environment variables for custom docker?

### ISSUE THREAD

**Issue by gnerativ** [basetenlabs/truss#1083]
**Problem**
For custom docker build commands, build commands is good but I think it only supports "RUN" now. If I were to export PATH variables there is no easy way

**SOLUTION**
If there is a way we can use ENV variables in build commands it should be good. So, in build commands if we start with ENV then instead of throwing error, it should take it as an ENV variable

Tried using single line export within RUN but its not good for multi line RUN commands

Its difficult for you to have different cuda versions of docker images. So, for custom cuda versions, this should help

**Comment by squidarth** [comment]
Hi @gnerativ  -- would it be possible to use the `environment_variables` feature for this? You should be able then use the values set here in your custom build commands.

**Comment by gnerativ** [comment]
Hi @squidarth yeah. There are workarounds. Got it working. Its just that I was expecting a proper docker build. But its not needed. Used a complete custom docker and it worked. Thanks.
