### ISSUE TITLE
Ignore __pycache__ directories when calculating patches for live_reload of truss

### ISSUE THREAD

**Issue by pankajroark** [basetenlabs/truss#138]
live_reload is great for quickly making changes to model serving code on a running truss on docker. But making changes to the model.py often creates a __pycache__ directory. live_reload mechanism doesn't understand this change and skip resulting in full build. This only happens first time, as the __pycache__ directory does not change afterwards, but it's still annoying. It would be great if we could simply ignore any __pycache__ directories.

**Comment by bolasim** [comment]
This is a duplicate of https://github.com/orgs/basetenlabs/projects/3?pane=issue&itemId=31855580
