### ISSUE TITLE
Ignore hidden and pycache files when building docker images and for live reload

### ISSUE THREAD

**Issue by pankajroark** [basetenlabs/truss#226]
Features such as live reload monitor for any changes to Truss, and if the changes are not supported then fallback to full build. Even for regular builds the whole truss directory is bundled, which means hidden directories such as `.git` also get bundled. It would be great to ignore hidden files and directories, and also pycache files for these. More could be added to this list, e.g. when  support for tests is added, the designated tests directory it could belong here.

In the long term, support for a .trussignore file could be useful, but it's not clear if there's an immediate need for it.

**Comment by bolasim** [comment]
@pankajroark how do you feel about having a template `.trussignore` (like [this](https://github.com/github/gitignore/blob/main/Python.gitignore) ) that's automatically copied into the truss when we template it out?
