### ISSUE TITLE
Support for model binary changes for live reload

### ISSUE THREAD

**Issue by pankajroark** [basetenlabs/truss#230]
Ultimately, we should support live reload to all parts of truss. The most important remaining part is the data section of the truss. 

A key challenge is transferring such large payloads for this. The current patch endpoint can't support this, it would be very clumsy to cram big binary blobs into the patch json. A separate endpoint is likely needed on the Control Proxy to upload large blobs. The patch endpoint can then be enhanced to accept the content hash of the blob.

**Comment by bolasim** [comment]
Duplicate of https://github.com/basetenlabs/truss/issues/228
