### ISSUE TITLE
Base image does not respect python version from truss

### ISSUE THREAD

**Issue by bolasim** [basetenlabs/truss#234]
**Describe the bug**
adding `python_version: py38` or `python_version: 3.8` to the truss config does not result in python version 3.8 being available in the resulting docker image.

**To Reproduce**

**Expected behavior**
Should install the correct logger version

I believe the issue is that the base image doesn't build based on the correct python version: https://github.com/basetenlabs/truss/blob/main/docker/base_images/base_image.Dockerfile.jinja#L41

**Comment by tugrulguner** [comment]
Hi Bola, if you provide more details about steps to reproduce this behaviour, I can work on this issue, I hope :)

**Comment by bolasim** [comment]
Hey Tugrul! Thanks for following up. It was quicker to put up a PR for the fix than describe the repro. Would really appreciate your reviews and comments on it though: https://github.com/basetenlabs/truss/pull/235
