### ISSUE TITLE
Add support for custom base image in Truss

### ISSUE THREAD

**Issue by bolasim** [basetenlabs/truss#236]
**Is your feature request related to a problem? Please describe.**
I am trying to deploy a NeMO Megatron based model using truss. The installation has a lot of dependencies that I cannot achieve using simply the provided `system_packages` and `python_requirements` features that truss provides. I have spent two days trying to resolve these issues but keep going down the rabbit hole of installing more things that happen to not work.

However, [NVIDIA provides a base image](https://github.com/NVIDIA/NeMo#docker-containers) that does work for all these kinds of models and includes all kinds of run-time optimizations that I would like to benefit from.

**Describe the solution you'd like**
I would like a `custom_base_image` config in the `config.yaml` for truss. If this custom image is provided, truss tries to use it for preparing the truss server, instead of the base gpu image. 

It's okay for this `custom_base_image` to not succeed in all cases. For example, if I use a base image that doesn't have a compatible python version, truss server might fail. I think that's okay given that this is a very advanced feature.

**Comment by bolasim** [comment]
There are a few potential approaches:

1. Use `custom_base_image` in place of the `base_image_name_and_tag` in `base.Dockerfile.jinja` and then add a few steps to make sure that server deps are installed (`pip install requirements.txt` should take care of it since the server python requirements are merged with the user right now).
2. We can use [`custom_base_image` in a multistep docker](https://docs.docker.com/build/building/multi-stage/#use-an-external-image-as-a-stage) build and copy certain paths from it to our docker image
3. We could do the inverse of 2. Start with `custom_base_image` and copy certain parts of `base_image_name_and_tag` that we know are needed for the server.

I am against 2 since it requires the user to be more verbose and know the details of the docker image that they are trying to use (which they won't know).

I think 1 is a quick short term solution that we can get out quickly and 3 could be a followup that is more robust (1 what would work if the base image has the python support that we're hoping for).

@pankajroark what do you think?

**Comment by pankajroark** [comment]
I'm ok with the option of a custom base image, with properly documented `discouraged` + `no guarantees`. @howespt wdyt?
