### ISSUE TITLE
"S3UploadFailedError: Failed to upload" while deploying custom model

### ISSUE THREAD

**Issue by armheb** [basetenlabs/truss#418]
**Describe the bug**
I'm trying to deploy my custom model. During the upload process I get the error when 95% is uploaded
**To Reproduce**
`my_model = truss.load("truss/model_1_truss")

baseten.deploy(
    my_model,
    model_name="model_1",
    #is_trusted=True # Uncomment to give the model access to secrets
)`

**Expected behavior**
successful deployment
**Screenshots/Logs**
`ClientError                               Traceback (most recent call last)
File [~/anaconda3/envs/diffusers/lib/python3.10/site-packages/boto3/s3/transfer.py:292](https://file+.vscode-resource.vscode-cdn.net/home/adam-west/Projects/tat_project/truss/~/anaconda3/envs/diffusers/lib/python3.10/site-packages/boto3/s3/transfer.py:292), in S3Transfer.upload_file(self, filename, bucket, key, callback, extra_args)
    291 try:
--> 292     future.result()
    293 # If a client error was raised, add the backwards compatibility layer
    294 # that raises a S3UploadFailedError. These specific errors were only
    295 # ever thrown for upload_parts but now can be thrown for any related
    296 # client error.

File [~/anaconda3/envs/diffusers/lib/python3.10/site-packages/s3transfer/futures.py:103](https://file+.vscode-resource.vscode-cdn.net/home/adam-west/Projects/tat_project/truss/~/anaconda3/envs/diffusers/lib/python3.10/site-packages/s3transfer/futures.py:103), in TransferFuture.result(self)
     99 try:
    100     # Usually the result() method blocks until the transfer is done,
    101     # however if a KeyboardInterrupt is raised we want want to exit
    102     # out of this and propagate the exception.
--> 103     return self._coordinator.result()
    104 except KeyboardInterrupt as e:

File [~/anaconda3/envs/diffusers/lib/python3.10/site-packages/s3transfer/futures.py:266](https://file+.vscode-resource.vscode-cdn.net/home/adam-west/Projects/tat_project/truss/~/anaconda3/envs/diffusers/lib/python3.10/site-packages/s3transfer/futures.py:266), in TransferCoordinator.result(self)
    265 if self._exception:
--> 266     raise self._exception
    267 return self._result

File [~/anaconda3/envs/diffusers/lib/python3.10/site-packages/botocore/httpsession.py:465](https://file+.vscode-resource.vscode-cdn.net/home/adam-west/Projects/tat_project/truss/~/anaconda3/envs/diffusers/lib/python3.10/site-packages/botocore/httpsession.py:465), in URLLib3Session.send(self, request)
    464 request_target = self._get_request_target(request.url, proxy_url)
...
    300             filename, '[/](https://file+.vscode-resource.vscode-cdn.net/)'.join([bucket, key]), e
    301         )
    302     )

S3UploadFailedError: Failed to upload [/tmp/tmpi9z5aa8t.tgz](https://file+.vscode-resource.vscode-cdn.net/tmp/tmpi9z5aa8t.tgz) to baseten-user-models-2971lo7k/organizations/nBr1erq/models/cd309110-de01-4551-8913-f266cf95ea18/models/cd309110-de01-4551-8913-f266cf95ea18/model.tgz: An error occurred (ExpiredToken) when calling the UploadPart operation: The provided token has expired.`
![image](https://github.com/basetenlabs/truss/assets/18460769/117be8f5-27b4-460a-b33d-5419e836007c)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Environment versions: python 3.10
 - Truss version: '0.4.9'

**Additional context**

**Comment by pankajroark** [comment]
There's a 15 min timeout on the upload token right now. We are looking to increase this timeout. cc @bolasim

**Comment by armheb** [comment]
Thank you. closing the issue.
