### ISSUE TITLE
Fix Truss 101 tutorial

### ISSUE THREAD

**Issue by bolasim** [basetenlabs/truss#556]
1. Clear glossary of terms
2. Intro and conclusion
3. Get rid of echo server in favor of just serving empty Truss
4. More testing and clearer instructions

**Comment by bolasim** [comment]
@philipkiely can you post an update here?

**Comment by philipkiely-baseten** [comment]
Gonna be putting up a PR for this tonight though it requires the bug bash changes to get in first
