### ISSUE TITLE
Clean up default truss

### ISSUE THREAD

**Issue by bolasim** [basetenlabs/truss#560]
There are some things we can do to make the created Truss more user-friendly:

* Drop type hints, they're distracting
* Better default predict function (one line)
* No data/ and packages/ directories
* Fewer empty config options (model_name is already set in the CLI command ticket)

**Comment by bolasim** [comment]
@squidarth @philipkiely any update here?

**Comment by squidarth** [comment]
Solved in https://github.com/basetenlabs/truss/pull/565
