### ISSUE TITLE
local_data_dir in external_data should allow more than one level of directory

### ISSUE THREAD

**Issue by nrhodes** [basetenlabs/truss#577]
**Describe the bug**
If I have more than one level of directory in local_data_dir, I get an error while building:
FileNotFoundError: [Errno 2] No such file or directory: '/build/context/data/weights/film_net/Style/saved_model'
**To Reproduce**
1. Create a truss.
2. Add an external_data field:
```
external_data:
  - url: whatever
    local_data_path: a/b/foo

```
**Expected behavior**
The build succeeds.
**Actual behavior**
```
File "/truss/decorators.py", line 7, in wrapper
Aug 16 5:15:48pm
    return func(*args, **kwargs)
Aug 16 5:15:48pm
  File "/truss/truss_handle.py", line 396, in docker_build_setup
Aug 16 5:15:48pm
    image_builder.prepare_image_build_dir(build_dir, use_hf_secret=use_hf_secret)
Aug 16 5:15:48pm
  File "/truss/contexts/image_builder/serving_image_builder.py", line 162, in prepare_image_build_dir
Aug 16 5:15:48pm
    download_external_data(self._spec.external_data, data_dir)
Aug 16 5:15:48pm
  File "/truss/util/download.py", line 28, in download_external_data
Aug 16 5:15:48pm
    path.parent.mkdir(exist_ok=True)
Aug 16 5:15:48pm
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
Aug 16 5:15:48pm
    self._accessor.mkdir(self, mode)

```

** suggested fix **
In `download_external_data`, add `parents=True` to the `mkdir` call:
`        path.parent.mkdir(exist_ok=True)
`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Environment versions [e.g. python versions, framework/package versions]
 - Truss version 0.5.8

**Comment by bolasim** [comment]
Thanks for the issue @nrhodes ! We'll take a look and propose a fix.

**Comment by pankajroark** [comment]
The suggested fix makes sense to me. Thanks @nrhodes

**Comment by squidarth** [comment]
Yes, thanks for reporting @nrhodes! Just put up a PR w/ your suggested fix
