### ISSUE TITLE
Prevent duplicate requirements with add_python_requirement

### ISSUE THREAD

**Issue by philipkiely-baseten** [basetenlabs/truss#68]
**Describe the bug**
When I run add_python_requirement and the requirement is already listed in config.yaml, it is listed again.

e.g.

```
requirements:
- joblib==1.0.0
- joblib==1.0.0
- joblib==1.1.0
```

**To Reproduce**

Run the add_python_requirement command twice with the same requirement

```
import truss

truss.init("test_truss")
tr = truss.from_directory("test_truss")
#tr.add_python_requirement("joblib==1.0.0")
#tr.add_python_requirement("joblib==1.0.0")
#tr.add_python_requirement("joblib==1.1.0")
```

**Expected behavior**

If the package is already a requirement, don't add it again.

If the package is already a requirement but I am specifying a different version, update the version rather than duplicating the entry.

Expected output of the above code sample:

```
requirements:
- joblib==1.1.0
```

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Environment versions: Python 3.7
 - Truss version: 0.0.30

**additional information**

Investigate whether the same thing happens for system requirements and fix it there, too!

**Comment by tugrulguner** [comment]
Hi, I wonder if this is still an issue?

**Comment by pankajroark** [comment]
> Hi, I wonder if this is still an issue?

I think it is.

**Comment by tugrulguner** [comment]
I can work on this if it's okay

**Comment by philipkiely-baseten** [comment]
That would be wonderful, thank you so much!

**Comment by tugrulguner** [comment]
This is great! thank you as well

**Comment by tugrulguner** [comment]
Hi, I'm working on this but it is not allowing me to create a branch, is there anything I should do to gain access?

**Comment by pankajroark** [comment]
You can create a PR using a fork: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by tugrulguner** [comment]
Sounds good! thank you

**Comment by tugrulguner** [comment]
This issue has been resolved! It was fun :)

**Comment by pankajroark** [comment]
Thanks @tugrulguner
