### ISSUE TITLE
sentence_transformers not working

### ISSUE THREAD

**Issue by aus70** [basetenlabs/truss#751]
**Describe the bug**
A simple example that uses `sentence-transformers/paraphrase-multilingual-mpnet-base-v2`, based on the code provided in the "Truss 101" tutorial does not work.

**To Reproduce**
To deploy the code (pasted below), follow the instructions in the "Truss 101" tutorial.

**Expected behavior**
An embedding vector should be returned by calling `truss predict -d '"Truss is awesome!"'`

**Screenshots/Logs**
Command line:
```
(baseten-experiments-py3.11) ➜  my-first-truss truss predict -d '"Truss is awesome!"'
{
  "error": "Model is not ready, it is still building or deploying"
}
```
```
Logs:
Nov 27 5:29:18pm
starting uvicorn with 1 workers
Nov 27 5:29:18pm
Executing model.load()...
Nov 27 5:29:18pm
Application startup complete.
Nov 27 5:29:25pm
Load pretrained SentenceTransformer: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Nov 27 5:29:36pm
Inference server seems to have crashed, restarting
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Environment versions: python 3.11.6
 - Truss version: 0.7.18

**Additional context**
Requirements:
```
requirements: [
  torch==2.0.1,
  sentence-transformers==2.2.2,
  hf-transfer==0.1.4
]
```
model.py:
```
from sentence_transformers import SentenceTransformer


class Model:
    def __init__(self, **kwargs):
        self._model = None

    def load(self):
        self._model = SentenceTransformer(
            "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
        )

    def predict(self, model_input):
        return self._model.encode([model_input])[0].tolist()
```

**Comment by squidarth** [comment]
Hi @aus70! By best guess from the error message that you're seeing is that the Trussis running out of memory and then crashing. Could you try running this on a larger instance? You can change this via the UI on baseten.

I'll also look into improving the error message here.

**Comment by squidarth** [comment]
If you take a look at the "metrics" tab, you can see the CPU memory usage below

<img width="715" alt="Falcon_7B___Model___Baseten" src="https://github.com/basetenlabs/truss/assets/850115/3f9fe14b-aacc-41c8-a6fa-1377a57f044f">

**Comment by aus70** [comment]
Memory was indeed the problem, I increased the RAM to 16GB (likely more than what's needed), and it works well. Thanks!

**Comment by squidarth** [comment]
no problem!
