### ISSUE TITLE
Can we specify custom .truss_ignore?

### ISSUE THREAD

**Issue by ynie** [basetenlabs/truss#780]
**Is your feature request related to a problem? Please describe.**
My trust folder also has `venv` and some local model files. It would be great to add them to the .truss_ignore, so I don't have to upload them each time.

**Describe the solution you'd like**
Read the local version of the .truss_ignore if it exists in the project directory.

**Describe alternatives you've considered**
Add venv to the .truss_ignore.

**Additional context**
None

Thank you!

**Comment by varunshenoy** [comment]
Hi Steven,

Thanks for this feature request — it's a great idea. I'll spend some time this afternoon working on it.

Varun

**Comment by varunshenoy** [comment]
Pushed a PR with `.truss_ignore` support yesterday. Works identically to a `.gitignore` in the root of your truss. Let me know if you have any questions!
