### ISSUE TITLE
baseten python package

### ISSUE THREAD

**Issue by bufferoverflow** [basetenlabs/truss#784]
**Describe the bug**

Sorry, I was unable to find the repo for the baseten python package. Maybe point me to the right location.

https://pypi.org/project/baseten/ requires types-pytz (>=2022.7.1.0,<2023.0.0.0) which causes conflicts with other dependencies

**To Reproduce**
- create a poetry based project
- install langfuse and baseten

**Expected behavior**

- baseten should not depend on types-pytz (<2023.0.0.0)

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Environment versions [e.g. python versions, framework/package versions]
 - Truss version [e.g. 22]

**Additional context**

**Comment by squidarth** [comment]
Hi @bufferoverflow -- thanks for the issue! I just made https://github.com/basetenlabs/baseten_client/pull/385 to loosen the restrictions around pytz, which we'll have out shortly.

Out of curiosity -- what are you using the `baseten` python lib for? Wanted to note that if you are using it for deploying models, the recommended way to use that is through the `truss` client (this repo).

**Comment by squidarth** [comment]
@bufferoverflow this is released as baseten==0.8.2

**Comment by bufferoverflow** [comment]
@squidarth thanks for the fast fix! It's used by https://github.com/BerriAI/litellm
