### ISSUE TITLE
Small Bug : API key Prompt appearing only for first time when using truss push  

### ISSUE THREAD

**Issue by Shivam-002** [basetenlabs/truss#790]
**Description**
I was new to truss, so when I used the truss push & it prompt me to enter the API key, that time I didn't have the key so I exited & created the api-key and come-back and again did truss push and this time no API key prompted, instead it said No API Key Provided.
(I then found that configure can be used to configure key using the --help, but the point is that it should prompt everytime)

**Screenshot**
![image](https://github.com/basetenlabs/truss/assets/61475044/1b9b4cf9-d017-493f-9d60-a9fb3b5fe205)

**Comment by squidarth** [comment]
Hey @Shivam-002, thanks for the issue! I just put up a PR to make this experience a little bit better, although I think there's more work we can do here.
