### ISSUE TITLE
Config 'model_cache' type: Truss push expects a list while baseten docker build seems to expect a dict when using Google Cloud Storage

### ISSUE THREAD

**Issue by IronJayx** [basetenlabs/truss#862]
**Describe the bug**

I am trying to use model caching with Google Cloud Storage. 

From the docs: https://truss.baseten.co/guides/model-cache#hugging-face

Truss seems to expect a dict in config.yaml as a value for model_cache when using GCS as a source. 

However if I do that:

`
model_cache:
  repo_id: 'gs://<path-to-my-bucket>'
`

I get

`
❯ truss push
ERROR: 'str' object has no attribute 'get'
`

On the other hand if I specify as a list:
`
model_cache:
  - repo_id: 'gs://<path-to-my-bucket>'
`
Truss push works but the build fails as it seems to expect a dict. See below error in Screenshots/Logs. 

Note: 
- I also tried with 'gcs://' as specified in the doc but I don't think this is right/ is a separate problem in any case
- I did include a service account at data/service_account.json

**Expected behavior**

**Screenshots/Logs**

`
Mar 12 11:13:16am
Setting up docker build context for truss
Mar 12 11:13:16am
  File "/scaffold/main.py", line 49, in <module>
Mar 12 11:13:16am
    tr.docker_build_setup(Path('/build/context'), use_hf_secret="HUGGING_FACE_HUB_TOKEN" in os.environ)
Mar 12 11:13:16am
  File "/truss/decorators.py", line 7, in wrapper
Mar 12 11:13:16am
    return func(*args, **kwargs)
Mar 12 11:13:16am
  File "/truss/truss_handle.py", line 417, in docker_build_setup
Mar 12 11:13:16am
    image_builder.prepare_image_build_dir(build_dir, use_hf_secret=use_hf_secret)
Mar 12 11:13:16am
  File "/truss/contexts/image_builder/serving_image_builder.py", line 616, in prepare_image_build_dir
Mar 12 11:13:16am
    self._render_dockerfile(
Mar 12 11:13:16am
  File "/truss/contexts/image_builder/serving_image_builder.py", line 663, in _render_dockerfile
Mar 12 11:13:16am
    dockerfile_contents = dockerfile_template.render(
Mar 12 11:13:16am
  File "/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
Mar 12 11:13:16am
    self.environment.handle_exception()
Mar 12 11:13:16am
  File "/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
Mar 12 11:13:16am
    raise rewrite_traceback_stack(source=source)
Mar 12 11:13:16am
  File "/truss/templates/server.Dockerfile.jinja", line 5, in top-level template code
Mar 12 11:13:16am
    {% extends "base.Dockerfile.jinja" %}
Mar 12 11:13:16am
  File "/truss/templates/base.Dockerfile.jinja", line 68, in top-level template code
Mar 12 11:13:16am
    {% for env_var_name, env_var_value in config.environment_variables.items() %}
Mar 12 11:13:16am
  File "/.venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
Mar 12 11:13:16am
    if hasattr(obj, "jinja_pass_arg"):
Mar 12 11:13:16am
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
Mar 12 11:13:17am
2024/03/12 10:13:17 Skipping step because a previous step failed
Mar 12 11:13:17am
2024/03/12 10:13:17 Skipping step because a previous step failed
`

**Comment by IronJayx** [comment]
Thanks,  you are right, it works now. There was a hint in the logs but I didn't catch it ;)

**Comment by squidarth** [comment]
>  Thanks, you are right, it works now. There was a hint in the logs but I didn't catch it ;)

glad to hear -- will still work on making those docs & ux fixes!
