### ISSUE TITLE
I follow the Quickstart to classify text but when I: $ truss predict -d '"Truss is awesome!"' . I get the error as follow, but when check log, it run normal

### ISSUE THREAD

**Issue by MrTuanDao** [basetenlabs/truss#932]
![image](https://github.com/basetenlabs/truss/assets/103438257/a34da804-ecfb-4870-92b3-b7acaa9687cb)
here is the log:
![image](https://github.com/basetenlabs/truss/assets/103438257/93949799-63d7-4d82-95f6-66ec2887d002)

**Comment by bolasim** [comment]
Hi @MrTuanDao . Thanks for reporting. Can you please tell us what version of truss you're using? You can find it with `truss --version`

**Comment by MrTuanDao** [comment]
> Hi @MrTuanDao . Thanks for reporting. Can you please tell us what version of truss you're using? You can find it with `truss --version`

Hi @bolasim, here is my truss version, I just open a pull request about fixing this by delete ["model_output"] behind of response.json(), it had been merged.
![image](https://github.com/basetenlabs/truss/assets/103438257/454c51fb-2fe6-4470-aa9c-67feb98cb0a6)
