### ISSUE TITLE
Allow specification of HTTP status code in predict() return.

### ISSUE THREAD

**Issue by RF5** [basetenlabs/truss#974]
**Is your feature request related to a problem? Please describe.**

If a prediction call fails, you cannot indicate to a caller _how_ or _why_ it failed. The status code is always either HTTP200 OK, or HTTP500 (if any exception is raised, even if you raise a custom Starlette HTTPError exception). 

**Describe the solution you'd like**

The truss `async def predict(self, request: Dict)` function should allow the user to return a custom HTTP return code. This can be done (I think?) simply by adding the following code:

```python
if isinstance(response, Response): 
    # user-provided predict function returned already packaged response, directly return it. 
    return response
```
To line 156 of the common truss server here: [https://github.com/basetenlabs/truss/blob/main/truss/templates/server/common/truss_server.py#L156](https://github.com/basetenlabs/truss/blob/main/truss/templates/server/common/truss_server.py#L156)

This way, a user-specified function can return a prepackaged Starlette Response object, with custom HTTP return code and header configuration. In addition to allowing the user to now return better error or accept status_codes (e.g. an HTTP 202 ACCEPTED response) , it also allows more advanced users to specify a custom way to packaging their response and its associated headers. 

**Describe alternatives you've considered**
- Tried to return internal status code inside the regular response dict of predict() function: this is too hacky and requires clients to check an internal `status_code` field of an HTTP200 OK response to double check if it is a satisfactory response. 
- Tried to raise a Starlette HTTPError or Response objects in the object caller, or to return them instead of raise them. These all result in an HTTP500 internal server error being thrown, not correctly returning the HTTPError or Response object raised/returned. 

**Additional context**
The goal here is to allow more advanced users to specify an HTTP status code in the response, and possibly insert custom headers or craft a non-trivial Starlette response for their custom use case.

**Comment by squidarth** [comment]
Hi @RF5  -- sorry the late response here.

We're working on a more comprehensive solution here along the lines of what you're proposing. In the meantime, you should be able to raise a `fastapi.HTTPException`:

```
    import fastapi

    class Model:
        def predict(self, request):
            raise fastapi.HTTPException(status_code=500, detail="My custom message.")
```


See our integration test to cover this case: https://github.com/basetenlabs/truss/blob/827f47bf78df7e634846ae168aa8fde4145a7104/truss/tests/test_model_inference.py#L751

**Comment by squidarth** [comment]
This is the the more canonical way of doing this now: https://docs.baseten.co/deploy/guides/responses
